export const REPORTS_5100 = [
  "01-LD - Chi tiêu QLKT lưới 110-500 kV",
  "2A-LD - Báo cáo tổng hợp điện năng giao nhận",
  "2B-LD - Báo cáo tổng hợp điện năng giao nhận",
  "2C-LD - Bảng tổng hợp điện năng giao nhận",
  "2D-LD - Điện năng giao nhận đầu nguồn",
  "2E-LD - Tổng hợp điện năng giao nhận",
  "03-LD - Báo cáo tình hình sự cố lưới điện 110kV - 500kV",
  "04-LD - Báo cáo công tác gây ngừng/giảm cung cấp điện trên lưới 110-500kV",
  "5A-LD - Báo cáo chi tiết thời gian điện áp vượt giới hạn cho phép của các nút",
  "5B-LD - Báo cáo chi tiết mức độ đầy tải và quá tải đường dây/MBA",
  "06-LD - Tổng hợp sự cố và suất sự cố DZ và TBA 110 - 500kV",
  "07-LD - Phân loại sự cố lưới điện 110kV - 500kV",
  "08-LD - Bảng tổng hợp độ tin cậy lưới 110 - 500kV",
  "09-LD - Tổng hợp chỉ tiêu QLKT lưới phân phối",
  "10-LD - Tình hình sự cố lưới điện trung, hạ áp",
  "11-LD - Công tác gây ngừng/giảm cung cấp điện trên lưới trung, hạ áp",
  "12-LD - Chi tiết mức độ mang tải đường dây trung áp",
  "13-LD - Vận hành MBA phân phối lưới điện trung, hạ áp",
  "14-LD - Tổng hợp số sự cố và suất sự cố DZ và TBA lưới trung, hạ áp",
  "15-LD - Chỉ số độ tin cậy lưới điện phân phối"
];

export const REPORTS_QT = [
  "NB-QLKT-Tình hình sự cố đường dây",
  "NB-QLKT-Tình hình sự cố trạm",
  "NB-QLKT-Tình hình sự cố TBA",
  "NB-QLKT-Tình hình đại tu, sửa chữa MBA",
  "NB-QLKT-Khối lượng thiết bị đang quản lý vận hành",
  "NB-QLKT-Tình hình sai hoặc hư hỏng của bảo vệ relay",
  "NB-QLKT-Thống kê TBA và MBA TG",
  "NB-QLKT-Thống kê khối lượng đường dây đang quản lý vận hành",
  "NB-QLKT-Thống kê TBA và MBA Phân Phối",
  "NB-QLKT-Thống kê TBA và MBA Tăng áp",
  "NB-QLKT-Thống kê MBA PP 35/0,4kV",
  "NB-QLKT-Thống kê MBA PP 22/0,4kV",
  "NB-QLKT-Thống kê thẻ tài sản cố định theo đường dây",
  "NB-QLKT-Thống kê MBA PP 10/0,4kV",
  "NB-QLKT-Thống kê tình hình quản lý máy cắt trong tháng",
  "NB-QLKT-Báo cáo chi tiết TSCĐ đang vận hành trên lưới",
  "NB-QLKT-Thống kê tài sản cố định đang vận hành trên lưới",
  "NB-QLKT-Thống kê khối máy bù và tụ điện đang quản lý vận hành",
  "NB-QLKT-Thống kê từng loại thiết bị",
  "NB-QLKT-Thống kê cáp ngầm thuộc tài sản điện lực",
  "NB-QLKT-Thống kê dao cách ly trung thế",
  "NB-QLKT-Thống kê TI trung thế",
  "NB-QLKT-Thống kê chống sét trung thế",
  "NB-QLKT-Bảng so sánh TSCĐ trên lưới với FMIS",
  "NB-QLKT-Thống kê TU trung thế",
  "NB-QLKT-Thống kê khối lượng trạm và máy biến áp 110KV",
  "Bảng kê chủng loại thiết bị trong TBA",
  "NB-QLKT-Kết quả kiểm tra kỹ thuật đường dây không",
  "NB-QLKT-Kết quả kiểm tra kỹ thuật MBA",
  "NB-QLKT-Tình hình kiểm tra kỹ thuật đường dây không",
  "NB-QLKT-Tình hình kiểm tra kỹ thuật MBA",
  "NB-QLKT-Thống kê số lần hoạt động của relay",
  "NB-QLKT-Thông số vận hành các trạm trung gian",
  "NB-QLKT-Danh sách máy biến áp mang tải",
  "NB-QLKT-Thông số phụ tải ngày"
];
